spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobdata
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:/config/liquibase/master.xml
    enabled: true
server:
  port: 8080
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
