name: mobiauto-backend-interview
services:
  mysql:
    image: mysql:8.4.0
    container_name: db-mob
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=mobdata
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 127.0.0.1:3306:3306
    command: mysqld --lower_case_table_names=1 --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
    healthcheck:
      test: ['CMD', 'mysql', '-e', 'SHOW DATABASES;']
      interval: 5s
      timeout: 5s
      retries: 10
